[package]
name = "chipbots-assembler"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
byteorder = "1.5.0"
pest = "2.7.15"
pest_derive = "2.7.15"
thiserror = "2.0.9"

[dev-dependencies]
chipbots-vm = { path = "../chipbots-vm" }
